# Generated by Django 4.2.1 on 2023-11-04 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("achievements", "0002_remove_achievement_level"),
    ]

    operations = [
        migrations.AddField(
            model_name="achievement",
            name="level",
            field=models.IntegerField(default=1),
        ),
    ]
